---
title: "Untitled"
author: "Syeda azra"
date: "20 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

```


```{r}
rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
mydata
dim(mydata)
summary(mydata$V9)

```

```{r}
colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

str(mydata)
#summary(mydata)
#unique.array(mydata)

```

```{r}

#combinting the columns
mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)

```

```{r}

#install.packages("dummies")
library(dummies)

mydata1<- dummy.data.frame(mydata, sep = ".")
mydata1<- mydata[,-9]
mydata1<- dummy.data.frame(mydata1,sep=".")

names(mydata1)
mydata1$Class<-mydata$Class
mydata1

```

```{r}
#install.packages('caTools')
library(caTools)
#install.packages("MASS")
library(MASS)
#install.packages("caret")
library(caret)

```

```{r}

#data partitioning

set.seed(1234)

train_rows<- createDataPartition(mydata1$Class, p = 0.7,list = F)

train <- mydata1[train_rows, ]

test  <- mydata1[-train_rows, ]
summary(test$Class)
summary(train$Class)


```

```{r}

library(e1071)
library(kernlab)

#model_svm_lnr <- svm(Class ~ . ,train, kernel = "linear")
#model_svm_an <- ksvm(Class ~ . , train, kernel = "anovadot")
model_svm_tn <- ksvm(Class ~ . , train, kernel = "tanhdot")

#summary(model_svm_lnr)
#summary(model_svm_an)
summary(model_svm_tn)

```


```{r}
# the confusion matrix 
# 
# library(MASS)
# library(caret)

 preds_svm <- predict(model_svm_lnr, test)
  preds_train_svm<-predict(model_svm_lnr,train)
 # 
 confusionMatrix(preds_svm, test$Class)
 # 
 confusionMatrix(preds_train_svm, train$Class)

```


```{r}


# the confusion matrix 

 preds_svm <- predict(model_svm_an, test)
 preds_train_svm<-predict(model_svm_an,train)
# 
 confusionMatrix(preds_svm, test$Class)
# 
 confusionMatrix(preds_train_svm, train$Class)

```


```{r}

# the confusion matrix 

preds_svm <- predict(model_svm_tn, test)
preds_train_svm<-predict(model_svm_tn,train)

confusionMatrix(preds_svm, test$Class)

confusionMatrix(preds_train_svm, train$Class)

```


```{r}

```

