---
title: "logistic regression"
author: "Syeda azra"
date: "19 September 2017"
output: html_document
---

```{r}

rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
dim(mydata)
summary(mydata$V9)
```








```{r}
colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

str(mydata)
summary(mydata)
unique.array(mydata)
```


```{r}
#combinting the columns
mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)
```



```{r}
sum(is.na(mydata))
```


```{r}
library(dummies)

mydata1<- dummy.data.frame(mydata, sep = ".")
mydata1<- mydata[,-9]
mydata1<- dummy.data.frame(mydata1,sep=".")

names(mydata1)
mydata1$Class<-mydata$Class
mydata1
```



```{r}
library(caret)
library(caTools)
library(MASS)
```


```{r}
#data partitioning

set.seed(1234)

train_rows<- createDataPartition(mydata1$Class, p = 0.7,list = F)

train <- mydata1[train_rows, ]

test  <- mydata1[-train_rows, ]

```


```{r}
#install.packages("glmnet")
library(glmnet)
library(Matrix)

reg <- model.matrix(Class~., data = train)
reg1 <- model.matrix(test$Class~., data = test)
log_reg<-glmnet(reg,train$Class,family = "multinomial",alpha =0)


#  x_train <- model.matrix( ~ .-1, train[,features])
# lm = cv.glmnet(x=x_train,y = as.factor(train$y), intercept=FALSE ,family =   "multinomail", alpha=1, nfolds=7)
# best_lambda <- lm$lambda[which.min(lm$cvm)]





```

```{r}
summary(log_reg)
```

```{r}
library(MASS)
library(caret)
preds_test_lr <- predict(log_reg, reg1,type = "class")
preds_train_lr<-predict(log_reg,train)
#test$Class<-as.data.frame(test$Class)
dim(preds_test_lr)
length(test$Class)
table(preds_test_lr, test$Class)

confusionMatrix(preds_train_lr, train$Class)
```



```{r}

```

```{r}



```

