---
title: "Untitled"
author: "Syeda azra"
date: "20 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
mydata
dim(mydata)
summary(mydata$V9)

```


```{r}
colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

str(mydata)
summary(mydata)
unique.array(mydata)

```

```{r}
#combinting the columns
mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)

```

```{r}
#install.packages("dummies")
library(dummies)

mydata1<- dummy.data.frame(mydata, sep = ".")
mydata1<- mydata[,-9]
mydata1<- dummy.data.frame(mydata1,sep=".")

names(mydata1)
mydata1$Class<-mydata$Class
mydata1

```

```{r}

#install.packages('caTools')
library(caTools)
#install.packages("MASS")
library(MASS)
#install.packages("caret")
library(caret)

```

```{r}
#data partitioning

set.seed(1234)

train_rows<- createDataPartition(mydata1$Class, p = 0.7,list = F)

train <- mydata1[train_rows, ]

test  <- mydata1[-train_rows, ]
summary(test$Class)
summary(train$Class)

```

```{r}
#decision tree model
#install.packages("C50")
library(C50)

#c5_tree <- C5.0(Class ~ . , train)

c5_rules <- C5.0(Class ~ . , train, rules = T)
summary(c5_rules)

```

```{r}
#important variable

C5imp(c5_tree, metric = "usage")
```

```{r}
plot(c5_tree)
```


```{r}
preds <- predict(c5_tree, test)
head(test)
preds1=predict(c5_tree,train)
```

```{r}
library(caret)
length(test$Class)

confusionMatrix(preds, test$Class)

confusionMatrix(preds1, train$Class)
```

