---
title: "Untitled"
author: "Syeda azra"
date: "11 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}

rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
dim(mydata)
summary(mydata$V9)

```






```{r}

colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

#str(mydata)
summary(mydata)
#unique.array(mydata)
```

```{r}
#combinting the columns
mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)
```

```{r}
sum(is.na(mydata))
```

```{r}
library(caret)
library(caTools)
library(MASS)
```



```{r}
set.seed(1234)

train_rows<- createDataPartition(mydata$Class, p = 0.7,list = F)

train <- mydata[train_rows, ]

test  <- mydata[-train_rows, ]

summary(test$Class)
summary(train$Class)
```



```{r}

train$Class<-as.character(train$Class)

train_not_vrecom<-train[which(train$Class %in% "not_recom" | train$Class %in% "very_recom"),]
table(train_not_vrecom$Class)
train_not_vrecom$Class<-as.factor(train_not_vrecom$Class)

train_remaining<-train[which(train$Class %in% "priority" | train$Class %in% "spec_prior"),]

train$Class<-as.factor(train$Class)

```

```{r}
library(vegan)
library(FNN)

model_knn=knn3(Class~.,train,k=9)

```


```{r}
preds_train_knn<-predict(model_knn,train,type = "class")
preds_test_knn <- predict(model_knn,test, type = "class")

```

```{r}
confusionMatrix(preds_test_knn, test$Class)

confusionMatrix(preds_train_knn, train$Class)
```

