---
title: "Untitled"
author: "Syeda azra"
date: "6 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
dim(mydata)
summary(mydata$V9)
```

```{r}
colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

#str(mydata)
summary(mydata)
#unique.array(mydata)
```

```{r}
#combinting the columns
mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)
```

```{r}
sum(is.na(mydata))
```

```{r}
library(dummies)

mydata1<- dummy.data.frame(mydata, sep = ".")
mydata1<- mydata[,-9]
mydata1<- dummy.data.frame(mydata1,sep=".")

names(mydata1)
mydata1$Class<-mydata$Class
mydata1
```

```{r}
library(caret)
library(caTools)
library(MASS)
```

```{r}
#data partitioning

set.seed(1234)

train_rows<- createDataPartition(mydata1$Class, p = 0.7,list = F)

train <- mydata1[train_rows, ]

test  <- mydata1[-train_rows, ]

summary(test$Class)
summary(train$Class)
```





```{r}
train$Class<-as.character(train$Class)

train_not_vrecom<-train[which(train$Class %in% "not_recom" | train$Class %in% "very_recom"),]
table(train_not_vrecom$Class)
train_not_vrecom$Class<-as.factor(train_not_vrecom$Class)

train_remaining<-train[which(train$Class %in% "priority" | train$Class %in% "spec_prior"),]

train$Class<-as.factor(train$Class)

```



```{r}
#smoting
library(dplyr)
library(DMwR)
train_not_vrecom$Class<-as.factor(train_not_vrecom$Class)
class(train_not_vrecom)
train_not_vrecom<-SMOTE(Class~., data = train_not_vrecom , perc.over =900,perc.under = 170,K=15)

summary(train_not_vrecom$Class)
```



```{r}
train1<-rbind(train_not_vrecom,train_remaining)
table(train1$Class)


dim(train1)
dim(train)
```




```{r}
library(vegan)
library(FNN)
```



```{r}

#model_knn=knn3(Class~.,train1,k=3)

#model_knn=knn3(Class~.,train1,k=5)

#model_knn=knn3(Class~.,train1,k=7)

model_knn=knn3(Class~.,train1,k=9)

#model_knn=knn3(Class~.,train1,k=11)


```


```{r}

preds_train_knn<-predict(model_knn,train1,type = "class")
preds_test_knn <- predict(model_knn,test, type = "class")

```




```{r}

confusionMatrix(preds_test_knn, test$Class)

confusionMatrix(preds_train_knn, train1$Class)

```

