---
title: "Untitled"
author: "Syeda azra"
date: "19 September 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
dim(mydata)
summary(mydata$V9)
```
```{r}
colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

str(mydata)
summary(mydata)
unique.array(mydata)

```

```{r}

#combinting the columns

mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)
```

```{r}
sum(is.na(mydata))
```

```{r}
library(dummies)

mydata1<- dummy.data.frame(mydata, sep = ".")
mydata1<- mydata[,-9]
mydata1<- dummy.data.frame(mydata1,sep=".")

names(mydata1)
mydata1$Class<-mydata$Class
mydata1

```

```{r}
library(caret)
library(caTools)
library(MASS)
```


```{r}
#data partitioning

set.seed(1234)

train_rows<- createDataPartition(mydata1$Class, p = 0.7,list = F)

train <- mydata1[train_rows, ]

test  <- mydata1[-train_rows, ]
```

```{r}

library(randomForest)
library(ggplot2)

```


```{r}
model_rf <- randomForest(Class ~ . ,data=train)

importance(model_rf)
```



```{r}
varImpPlot(model_rf)
```


```{r}
library(MASS)
library(caret)
preds_rf <- predict(model_rf, test)
preds_train_rf<-predict(model_rf,train)

confusionMatrix(preds_rf, test$Class)

confusionMatrix(preds_train_rf, train$Class)
```










