---
title: "Untitled"
author: "Syeda azra"
date: "20 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls(all=TRUE))

setwd("C:\\Users\\Hi\\Desktop\\internship")

mydata<-read.csv("nursery.csv",header=F,sep=",")
dim(mydata)
summary(mydata$V9)

```

```{r}

colnames(mydata) <- c("parents","has_nurs","form","children","housing","finance","social","health","Class")

#str(mydata)
summary(mydata)
#unique.array(mydata)

```

```{r}
#combinting the columns
mydata$Class<-as.character(mydata$Class)
mydata$Class[mydata$Class=="recommend"]="very_recom"
mydata$Class<-as.factor(mydata$Class)
summary(mydata$Class)
```

```{r}
sum(is.na(mydata))
```

```{r}
library(dummies)

mydata1<- dummy.data.frame(mydata, sep = ".")
mydata1<- mydata[,-9]
mydata1<- dummy.data.frame(mydata1,sep=".")

names(mydata1)
mydata1$Class<-mydata$Class
mydata1
```

```{r}
library(caret)
library(caTools)
library(MASS)
```


```{r}
#data partitioning

set.seed(1234)

train_rows<- createDataPartition(mydata1$Class, p = 0.7,list = F)

train <- mydata1[train_rows, ]

test  <- mydata1[-train_rows, ]

summary(test$Class)
summary(train$Class)
```



```{r}
#install.packages("glmnet")
library(glmnet)
library(Matrix)

reg <- model.matrix(Class~., data = train)
reg1 <- model.matrix(test$Class~., data = test)

 lm = cv.glmnet(reg,train$Class,family = "multinomial",alpha =1)
 lm$lambda.min
log_reg<-glmnet(reg,train$Class,family = "multinomial",alpha =0,lambda = lm$lambda.min)


#  x_train <- model.matrix( ~ .-1, train[,features])
```

```{r}
summary(log_reg)
```


```{r}
library(MASS)
library(caret)

preds_test_lr <- predict(log_reg, reg1,type = "class")
preds_train_lr<-predict(log_reg, reg,type = "class")



confusionMatrix(preds_test_lr, test$Class)

confusionMatrix(preds_train_lr, train$Class)
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

